server:
  port: 8140

spring:
  data:
    mongodb:
      uri: mongodb://mongouser:test@localhost:27019/cart?authSource=admin
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
