spring:
  application:
    name: "cart-service"
  data:
    mongodb:
      uri: mongodb://mongouser:test@localhost:27019/cart?authSource=admin
      database: cart
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: create
server:
  port: 8140

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true


