spring:
  datasource:
    url: jdbc:mysql://localhost:3307/customer?useSSL=false&serverTimezone=UTC
    username: mysql
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
