spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
