spring:
  datasource:
    url: jdbc:postgresql://postgres_5434:5432/identity
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
