spring:
  data:
    mongodb:
      uri: mongodb://mongouser:test@mongo_27018:27017/product?authSource=admin
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
