spring:
  application:
    name: "product-service"
  data:
    mongodb:
      uri: mongodb://mongouser:test@localhost:27018/product?authSource=admin
      database: product
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: productCreatedFunction
      bindings:
        productCreatedFunction-out-0:
          destination: product-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8130

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
